kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: 'Build image'
    commands:
      - >
        docker build
        --no-cache
        --tag novakovd/tsa:$(git rev-parse --short HEAD)
        .
  - name: 'Run image'
    commands:
      - >
        docker run -d --rm
        --name tsa-rc
        --env APP_HOSTNAME=tsa-rc
        --network tsa-tests
        -v ./src:/app/src
        -v ./tests:/app/tests
        novakovd/tsa:$(git rev-parse --short HEAD)
  - name: 'Install npm dependencies'
    commands:
      - >
        docker exec -i
        tsa-rc
        npm i
  - name: 'Run unit tests'
    commands:
      - >
        docker exec -i
        tsa-rc
        npm run tests:run:unit
  - name: 'Run functional tests'
    commands:
      - >
        docker exec -i
        tsa-rc
        npm run tests:run:functional
  - name: 'Build e2e tests'
    commands:
      - >
        docker run -i --rm
        --network tsa-tests
        --env PORT=8080
        --name tsa-tests-builder
        -v ./:/srv -w /srv node:19-alpine
        sh -c "npm i && find tests -name "*.ts" | xargs npx tsc >> /dev/null"
  - name: 'Run e2e tests'
    commands:
      - >
        docker run -i --rm
        --env CYPRESS_baseUrl=http://tsa-rc:8080
        --name tsa-e2e-tester
        --network tsa-tests
        -v ./:/e2e -w /e2e cypress/included:12.8.1
        --browser chrome
  - name: 'Push to DockerHub'
    commands:
      - echo $PASSWORD | docker login -u $USERNAME --password-stdin
      - docker push novakovd/tsa:$(git rev-parse --short HEAD)
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
  - name: 'Push to GitHub'
    commands:
      - push-github git@github.com:novakovd/tsa.git
  - name: "Cleanup"
    commands:
      - docker stop tsa-rc
    when:
      status:
        - success
        - failure
